"""
Миграция для приложения restaurant_ordering.
"""

# Generated by Django 4.2.1 on 2024-09-13 15:55
# pylint: skip-file

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Миграция для создания начальных моделей приложения."""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=50,
                                          null=True,
                                          verbose_name='Имя покупателя')),
                ('phone_number', models.CharField(max_length=35,
                                                  verbose_name='Номер телефона покупателя')),
                ('address', models.TextField(blank=True,
                                             null=True,
                                             verbose_name='Адрес доставки')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name_product', models.CharField(max_length=200,
                                                  verbose_name='Наименование блюда')),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(max_length=500,
                                                 null=True,
                                                 verbose_name='Состав')),
                ('price', models.DecimalField(decimal_places=2,
                                              max_digits=6,
                                              verbose_name='Цена')),
                ('created', models.DateTimeField(auto_now_add=True,
                                                 verbose_name='Дата добавления в меню')),
                ('updated', models.DateTimeField(auto_now_add=True,
                                                 verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('name_product',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True,
                                                       verbose_name='Дата создания заказа')),
                ('amount', models.DecimalField(decimal_places=2,
                                               max_digits=6,
                                               verbose_name='Сумма заказа')),
                ('comment', models.TextField(blank=True,
                                             null=True,
                                             verbose_name='Комментарий к заказу')),
                ('status_cook', models.BooleanField(default=False,
                                                    verbose_name='Статус приготовления заказа')),
                ('status_delivery', models.BooleanField(default=False,
                                                        verbose_name='Статус доставки')),
                ('payment_state', models.BooleanField(default=False,
                                                      verbose_name='Статус оплаты')),
                ('update_time', models.DateTimeField(auto_now=True,
                                                     verbose_name='Дата изменения заказа')),
                ('customer', models.ForeignKey(blank=True,
                                               null=True,
                                               on_delete=django.db.models.deletion.CASCADE,
                                               to='restaurant_ordering.customer',
                                               verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1,
                                                         verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2,
                                              max_digits=6,
                                              verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=2,
                                                 default=0,
                                                 max_digits=6,
                                                 verbose_name='Скидка в %')),
                ('order', models.ForeignKey(null=True,
                                            on_delete=django.db.models.deletion.CASCADE,
                                            to='restaurant_ordering.order', verbose_name='id заказа')),
                ('product', models.ForeignKey(null=True,
                                              on_delete=django.db.models.deletion.CASCADE,
                                              to='restaurant_ordering.menu',
                                              verbose_name='Наименование продукта')),
            ],
            options={
                'verbose_name': 'Продукт в заказе',
                'verbose_name_plural': 'Продукт в заказе',
                'ordering': ['pk'],
            },
        ),
    ]
